version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: rent-service-db
    environment:
      POSTGRES_DB: rent_service_db
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - immo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rental_user -d rent_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  immo:
    external: true 