
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: rent-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://rent-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/v1/apartments/**
    networks:
      - immo
    restart: unless-stopped

networks:
  immo:
    external: true 