spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/immofinder_test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
